name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: cloudrun-github-demo
  REGION: us-central1
  REPO: my-repo
  IMAGE: my-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ WIF Authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/XXXX/locations/global/workloadIdentityPools/github-pool03/providers/provider10
          service_account: github-wif@cloudrun-github-demo.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      # ✅ STEP 2 STARTS HERE
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest \
            -f app/Dockerfile .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest
      # ✅ STEP 2 ENDS HERE

      # ✅ Terraform
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
