name: Deploy Cloud Run with Terraform (WIF)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test authentication
        run: gcloud auth list

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/386782938570/locations/global/workloadIdentityPools/github-pool03/providers/github-provider"
          service_account: "github-actions-sa@cloudrun-github-demo.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cloudrun-github-demo

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Build & Push Docker image
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          docker build -t us-central1-docker.pkg.dev/cloudrun-github-demo/my-repo/my-app:latest .
          docker push us-central1-docker.pkg.dev/cloudrun-github-demo/my-repo/my-app:latest

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        run: |
         cd terraform
         terraform init
         terraform apply -auto-approve \
          -var="project_id=cloudrun-github-demo" \
          -var="image=us-central1-docker.pkg.dev/cloudrun-github-demo/my-repo/my-app:latest"




